name: quick_pdf
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  image_picker: ^1.2.1
  mobx: ^2.3.0
  flutter_mobx: ^2.2.0
  build_runner: ^2.4.7
  mobx_codegen: ^2.6.0
  path_provider: ^2.0.14
  pdf: ^3.10.1
  path: ^1.9.0
  share_plus: ^10.1.2
  open_file: ^3.3.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
